led.plotBrightness(0 + 2, 0 + 2, 100)
led.plot(0, 0)
led.plot(1, 1)
let A = 0
let B = 0
input.onButtonPressed(Button.A, function on_button_pressed_a() {
    
    A = 1
    B = 1
    while (A == 1) {
        basic.clearScreen()
        led.plotBrightness(0 + 2, 0 + 2, 100)
        led.plot(0, 2)
        led.plot(1, 2)
        basic.pause(500)
        basic.clearScreen()
        led.plotBrightness(0 + 2, 0 + 2, 100)
        led.plot(0, 4)
        led.plot(1, 3)
        basic.pause(500)
        basic.clearScreen()
        led.plotBrightness(0 + 2, 0 + 2, 100)
        led.plot(2, 4)
        led.plot(2, 3)
        basic.pause(500)
        basic.clearScreen()
        led.plotBrightness(0 + 2, 0 + 2, 100)
        led.plot(4, 4)
        led.plot(3, 3)
        basic.pause(500)
        basic.clearScreen()
        led.plotBrightness(0 + 2, 0 + 2, 100)
        led.plot(4, 2)
        led.plot(3, 2)
        basic.pause(500)
        basic.clearScreen()
        led.plotBrightness(0 + 2, 0 + 2, 100)
        led.plot(4, 0)
        led.plot(3, 1)
        basic.pause(500)
        basic.clearScreen()
        led.plotBrightness(0 + 2, 0 + 2, 100)
        led.plot(2, 0)
        led.plot(2, 1)
        basic.pause(500)
        basic.clearScreen()
        led.plotBrightness(0 + 2, 0 + 2, 100)
        led.plot(0, 0)
        led.plot(1, 1)
        basic.pause(500)
    }
})
input.onButtonPressed(Button.B, function on_button_pressed_b() {
    
    A = 0
    B = 0
    while (B == 0) {
        basic.clearScreen()
        led.plotBrightness(0 + 2, 0 + 2, 100)
        led.plot(2, 0)
        led.plot(2, 1)
        basic.pause(500)
        basic.clearScreen()
        led.plotBrightness(0 + 2, 0 + 2, 100)
        led.plot(4, 0)
        led.plot(3, 1)
        basic.pause(500)
        basic.clearScreen()
        led.plotBrightness(0 + 2, 0 + 2, 100)
        led.plot(4, 2)
        led.plot(3, 2)
        basic.pause(500)
        basic.clearScreen()
        led.plotBrightness(0 + 2, 0 + 2, 100)
        led.plot(4, 4)
        led.plot(3, 3)
        basic.pause(500)
        basic.clearScreen()
        led.plotBrightness(0 + 2, 0 + 2, 100)
        led.plot(2, 4)
        led.plot(2, 3)
        basic.pause(500)
        basic.clearScreen()
        led.plotBrightness(0 + 2, 0 + 2, 100)
        led.plot(0, 4)
        led.plot(1, 3)
        basic.pause(500)
        basic.clearScreen()
        led.plotBrightness(0 + 2, 0 + 2, 100)
        led.plot(0, 2)
        led.plot(1, 2)
        basic.pause(500)
        basic.clearScreen()
        led.plotBrightness(0 + 2, 0 + 2, 100)
        led.plot(0, 0)
        led.plot(1, 1)
        basic.pause(500)
    }
})
